### ISSUE TITLE
Weird simulated result in LevelSetLiquidSim

### ISSUE THREAD

**Issue by Snowapril** [utilForever/CubbyFlow#100]
**Describe the bug**
In the first example of LevelSetLiquidSim, simulated result is weird like below.

**Screenshots**

https://user-images.githubusercontent.com/24654975/116342791-2947f900-a81e-11eb-86d3-7799bc47d6ab.mp4

**Comment by utilForever** [comment]
Thanks for the report! I'll fix it soon. 😢

**Comment by utilForever** [comment]
@Snowapril Can you confirm the fix in #102? Thanks!

**Comment by Snowapril** [comment]
https://user-images.githubusercontent.com/24654975/117107812-2a989900-adbd-11eb-8516-45851b92be6b.mp4



LevelSetLiquidSim work correctly now! Great work!

**Comment by utilForever** [comment]
I'll close this issue after PR is merged.

**Comment by Snowapril** [comment]
Ok. Sorry for closed issue by myself 😂

**Comment by utilForever** [comment]
I merged the code that fixes this issue. Thanks for the report! :D
