### ISSUE TITLE
Update googlebenchmark to fix issue with gcc compilation

### ISSUE THREAD

**Issue by FederAndInk** [utilForever/CubbyFlow#108]
**Describe the bug**

googlebenchmark has a missing header `<limits>` which cause a compilation error with gcc

```
In file included from CubbyFlow/Libraries/googlebenchmark/src/benchmark_register.cc:15:
CubbyFlow/Libraries/googlebenchmark/src/benchmark_register.h:22:30: error: no member named 'numeric_limits' in namespace 'std'
```

it's fixed in the latest version (tag v1.5.5), just a submodule update

**Desktop (please complete the following information):**
 - OS: ArchLinux kernel 5.12.15
 - gcc: 11.1.0

**Comment by utilForever** [comment]
@FederAndInk Thanks for report! I'll fix it soon. 😉
