### ISSUE TITLE
makeTranslationMatrix should be transposed

### ISSUE THREAD

**Issue by yangfengzzz** [utilForever/CubbyFlow#125]
The Matrix is row-major so the translation part should be on ele[12], ele[13] ele[14]

**Comment by utilForever** [comment]
I know that Matrix is column-major, but is there a reason why you think row-major?

**Comment by yangfengzzz** [comment]
> I know that Matrix is column-major, but is there a reason why you think row-major?

Maybe I make a mistake, I found the matrix in fluid-engine-developmemt is row-major.

**Comment by utilForever** [comment]
fluid-engine-dev is column-major, too.
```cpp
template <typename T>
T& Matrix<T, 4, 4>::operator()(size_t i, size_t j) {
    return _elements[4 * i + j];
}

template <typename T>
const T& Matrix<T, 4, 4>::operator()(size_t i, size_t j) const {
    return _elements[4 * i + j];
}
```

**Comment by yangfengzzz** [comment]
Thx, I read the v1 code, it is different.

```
//!
//! \brief 2-D matrix class.
//!
//! This class is a row-major 2-D matrix class, which means each element of
//! the matrix is stored in order of (0, 0), (0, 1), (1, 0) and (1, 1).
//! \tparam T - Type of the element.
//!
template <typename T>
class Matrix<T, 2, 2> {
};
```

**Comment by utilForever** [comment]
Oh, I confused row-major and column-major. fluid-engine-dev and CubbyFlow are row-major. 😭 
Nice catch! I'll fix it ASAP. 😉 
Reference: https://www.scratchapixel.com/lessons/mathematics-physics-for-computer-graphics/geometry/row-major-vs-column-major-vector

**Comment by utilForever** [comment]
@yangfengzzz I discussed this issue with Doyub Kim. (https://github.com/doyubkim/fluid-engine-dev/issues/323)

**Comment by doyubkim** [comment]
Please see my latest comment in the other issue in fluid-engine-dev. Hope that addresses the confusion.

**Comment by utilForever** [comment]
@yangfengzzz I'll close this issue. Thanks. 🍡

**Comment by yangfengzzz** [comment]
Ok, I got it. With row major matrix and column vector, the code is correct. But I think it is better to use row major matrix with row vector or column matrix with column vector. Because when I use the matrix for Metal or OpenGL, the matrix have to be transposed then send to GPU.

**Comment by utilForever** [comment]
@yangfengzzz Can you open another issue to refactor it?
