### ISSUE TITLE
Couldn't find demo file link

### ISSUE THREAD

**Issue by rinechran** [utilForever/CubbyFlow#64]
I can't find the demo file link in readme.md 

the Url is https://github.com/utilForever/CubbyFlow-v0/tree/master/Demos  and check this link

**Comment by rinechran** [comment]
Isn't the correct address https://github.com/utilForever/CubbyFlow-v0/tree/master/Examples?

**Comment by utilForever** [comment]
Thanks! I'll fix it later. :)
