### ISSUE TITLE
Replace library 'Clara' with 'Lyra'

### ISSUE THREAD

**Issue by utilForever** [utilForever/CubbyFlow#68]
Recently, I found that the library 'Clara' (https://github.com/catchorg/Clara) is no longer maintained.
It has been forked and maintained as the new name 'Lyra' (https://github.com/bfgroup/Lyra).
We should replace it to maintain dependency.

**Comment by Snowapril** [comment]
#69 
I added **'Lyra'** submodule and modified the example codes which depend on **'Clara'**.
As 'Clara' submodule isn't removed yet, entirely removing it from our project is needed after testing.

**Comment by Snowapril** [comment]
Seems to properly work but, **help** text is printed out differently.

SPHSim --help (before)
![image](https://user-images.githubusercontent.com/24654975/73632305-aaa5ef80-469e-11ea-919f-53dd7658ca45.png)

SPHSim --help  (after)
![image](https://user-images.githubusercontent.com/24654975/73632711-f311dd00-469f-11ea-8dee-47e81ff52e43.png)

I found the [exactly same issue in the Lyra github](https://github.com/bfgroup/Lyra/issues/10).
It was created at 2019.10.8 and cant find any improvement about the problem.
