### ISSUE TITLE
CubicSemiLagrangian failed

### ISSUE THREAD

**Issue by yangfengzzz** [utilForever/CubbyFlow#99]
The Manual tests for CubicSemiLagrangian failed and Smoke simulation using CubicSemiLagrangian is failed too.
![rev0628_#grid2,iso](https://user-images.githubusercontent.com/5378042/116179252-93db3500-a749-11eb-8893-07e1b4fc02d3.png)

**Comment by utilForever** [comment]
@yangfengzzz Thanks for the report! I recently refactored many codes for preparing GPU support. I'll check it after the refactoring.

**Comment by utilForever** [comment]
@yangfengzzz BTW, I've been following you for a long time and watching your projects. Thank you for building my project and reporting the bug by writing an issue.

**Comment by yangfengzzz** [comment]
> @yangfengzzz Thanks for the report! I recently refactored many codes for preparing GPU support. I'll check it after the refactoring.

Actually I'm working on GPU too and looking at the branch dev-v2-gpu in fluid-engine-dev. This seems to be a bug that existed a long time ago.

**Comment by utilForever** [comment]
> > @yangfengzzz Thanks for the report! I recently refactored many codes for preparing GPU support. I'll check it after the refactoring.
> 
> Actually I'm working on GPU too and looking at the branch dev-v2-gpu in fluid-engine-dev. This seems to be a bug that existed a long time ago.

Is exists this bug in the main branch, too?

**Comment by yangfengzzz** [comment]
@utilForever  the main branch in fluid-engine-dev is correct. 
![rev0628_#grid2,iso](https://user-images.githubusercontent.com/5378042/116183652-d94f3080-a750-11eb-9fa2-e42cba38053d.png)

**Comment by utilForever** [comment]
@yangfengzzz Thanks! I'll compare the two branches and fix the problem. 🛩️

**Comment by utilForever** [comment]
@yangfengzzz Can you confirm the fix in #102? Thanks!

**Comment by yangfengzzz** [comment]
@utilForever It fixed well, Thx! But I think there should be no change for GetBarycentric at line 458, because GetBarycentric already concern about the boundary cases.

**Comment by utilForever** [comment]
@yangfengzzz Oh, it's my mistake! I'll fix it.

**Comment by utilForever** [comment]
@yangfengzzz I rollbacked the code at line 458 and merged it. Thanks for the report! :D
